SVG Decoder with Batik
Kamel-Media/Kamel pull request #50
Opened 2023-07-19 16:34 UTC by DATL4G

This adds Batik support for the SVG Decoder on the JVM.

As described in the `KamelConfigBuilder` extension function this is useful for this bug https://bugs.chromium.org/p/skia/issues/detail?id=12251

When using `svgDecoder(useBatik = true)` images [like this](https://github.com/Kamel-Media/Kamel/issues/42#issuecomment-1605812270) are displayed properly, however they may result in lower quality therefore this options is disabled by default.

2023-07-19 22:10 UTC, luca992 commented
It would make more sense to make a new decoder

2023-07-19 22:16 UTC, DATL4G commented
Mhm I don't know. They serve the same purpose and only one decoder can be used at a time.
An internal change would be required since the default KamelConfig already uses the SVGDecoder.

With the current implementation the decoder can be easily overwritten

2023-07-20 01:29 UTC, luca992 commented
> Mhm I don't know. They serve the same purpose and only one decoder can be used at a time. An internal change would be required since the default KamelConfig already uses the SVGDecoder.
> 
> With the current implementation the decoder can be easily overwritten

I think it should work something like this where the last added decoder of a type should replace any previously added decoders of the same type.

```kotlin
KamelConfig {
    takeFrom(KamelConfig.Default)
    resourcesFetcher()
    // the last added svg decoder should replace the default
    batikSvgDecoder(true)
}
```

2023-07-20 01:30 UTC, luca992 commented
Also... we should probably separate decoders into their own modules people can import independently.... but I can figure that out after

2023-07-20 12:49 UTC, DATL4G commented
I updated the PR so there is a separate decoder for Batik.

I don't think we should separate decoders into their own modules as this is a lot of overhead in development, I can tell as someone who developed other multi-module libraries.

I think a feature-like separation makes more sense.

Example:

We have a core image processing library which contains just default compose implementation.
Then we have a module for web resources, so all fetchers and decoders related to HttpRequests etc. are going in one extra module, as some people don't need this if they work with resources and system files only.
Then there is a svg module for example where all extra svg decoders (like Batik) take a place.

However there has to be a decision made about something like the android svg decoder. As the core images module would include the skia implementation and people could get confused why SVGs work on any other than android

2023-07-20 19:40 UTC, luca992 commented
Yeah I agree it should definitely be split up by features as well. But, if for example a svg decoder feature module one day has 5 different implementations backed by 5 different dependencies. People aren't going to like all that extra baggage. 

I think it might be good to split all the decoders / fetchers into their own modules then have a module called something like `kamel-defaults` or something similar which gives you access to `KamelConfig.Default` and exposes all decoders and fetchers which are considered default. And then you can also have another module which bundles by feature like `kamel-decoder-svg` which would expose all `svg` decoder implementations. And finally you can granular imports with each decoder/fetcher implementation like: `kamel-decoder-svg-batik`

```kotlin
dependencies {
    implementation("media.kamel:kamel-image:0.6.0")
    // imports all default implementations
    implementation("media.kamel:kamel-defaults:0.6.0") 
    // imports all svg decoders the (standard + batik)
    implementation("media.kamel:kamel-decoder-svg:0.6.0")
    // imports just the batik svg decoder
    implementation("media.kamel:kamel-decoder-svg-batik-:0.6.0")
    // ...
}
```

2023-07-20 19:45 UTC, luca992 requested changes

2023-07-20 19:45 UTC, luca992 commented on kamel-image/src/desktopMain/kotlin/io/kamel/image/config/DesktopKamelConfig.kt
> +import io.kamel.image.decoder.SvgDecoder
can you just clean up the imports

2023-07-20 19:45 UTC, luca992 commented on kamel-image/src/desktopMain/kotlin/io/kamel/image/decoder/DesktopSvgDecoder.kt
> +import javax.imageio.ImageIO
same here

2023-07-20 22:27 UTC, DATL4G commented
Done

2023-07-21 03:31 UTC, merged